name = "so-khop-xo-so"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

[[kv_namespaces]]
binding = "KV"
id = "93217aff02d548998ec3557daefb277a"

[vars]
ENVIRONMENT = "production"

# Cron Triggers: 18:10 GMT+7 thứ 4 và thứ 7 (11:10 UTC)
[triggers]
crons = ["10 11 * * 3,6"]
